### ISSUE TITLE
Problem with subfolder wordpress installation

### ISSUE THREAD

**Issue by brousse** [salendron/Pingeborg#12]
The plugin was not working on my wordpress test site due to the installation home directory (http://localhost/wordpress/)

in the pingeb_links.php, the $req containt the full path (with wordress folder) and cannot match the nfc, qr, api, ... url

here is my replacement code (i am not a reel developper so it's let's say an example to well understand the issue...)

replace
    $req = trim($_SERVER["REQUEST_URI"], '/');
with
    $req = str_replace(home_url(),'',((!empty($_SERVER['HTTPS'])) ? "https://" : "http://").$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI']);
    $req = trim($req, '/');

**Comment by salendron** [comment]
Bin dran. Wird behoben. Muss nur erst eine Testinstallation machen.

**Comment by salendron** [comment]
Done.
