### ISSUE TITLE
Links im Plugin

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#15]
Wo kommt man zu den API-Keys für Google Maps und Twitter.
Könnte man da einen Link im Plugin hinzufügen, um das offensichtlich zu machen?

Und die Begriffe gleich benennen wir in der jeweiligen Dev-Site:
z.B. "Access token" statt "User Token"

**Comment by salendron** [comment]
Jetzt check ich das erst. Ja wird gemacht! ;-)

**Comment by salendron** [comment]
Im Settings Header gibt's nun eine Erklärung und Links zu den Seiten für die Keys. Word bzgl. Twitterdaten angepasst.
