### ISSUE TITLE
Statistik

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#18]
In Graz scheint die Installation nicht zu zählen.

New Feature: Number of deployed locations im Widget.

**Comment by salendron** [comment]
Wie sie zählt nicht? Hat doch 2 Downloads gestern? 
Widget ist bereits erweitert. Zumindest auf Pingeb.org die Grazer Seite kann ich nicht aktualisieren. Zeigt die auf ein anderes Directory, also nicht auf p.graz?

**Comment by salendron** [comment]
Done.
