### ISSUE TITLE
Text im Plugin-Feld

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#19]
Dzt noch wenig aussagekräftig: 
https://www.facebook.com/photo.php?fbid=561072973918442&set=a.475518315807242.127256.468133103212430&type=1&relevant_count=1

Besser wäre:
"A plugin that connects the real world with your great content on WordPress using NFC, QR and geofences."

**Comment by salendron** [comment]
Done in version 1.0.0.5
