### ISSUE TITLE
WordPress.org - Other Notes

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#20]
In die Readme gehört noch etwas rein. Unter http://wordpress.org/extend/plugins/pingeborg/other_notes/

= Thank You =
The project was supported by the Internet Foundation Austria (IPA). More at [netidee.at](http://netidee.at).

Müssen dort nicht auch alle Libraries und andere OpenSource-Teile rein?
Kann ich die Datei direkt auch bearbeiten und hochladen? Wohin?

**Comment by salendron** [comment]
Theoretisch kannst du das bearbeiten. Nur musst du es dann ins SVN commiten. Hast du schon mal mit SVN gearbeitet?

**Comment by ghost** [comment]
Nope :-(
Reden wir das am Abend aus.

**Comment by salendron** [comment]
Steht ab 1.0.0.5 drin
