### ISSUE TITLE
Twitter Demenz

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#24]
Nach der Änderung von Tweet-Meldungen vergisst das Plugin ein wenig davon und schneidet willkürlich ab.
Zumindest trotzdem in der DB?

**Comment by salendron** [comment]
Ijn der DB sicher. Twitter passiert als Letztes. Kann es sein, dass wir hier und da in Kombination mit Tagnamen über 140 Zeichen kommen und Twitter deshalb schneidet?
