### ISSUE TITLE
Writing Tags

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#28]
Bin grad beim NFC-Tag-Beschreiben.
Das ist voll mühsam, weil ich alle URLs am Handy abtippe.

Wäre es nicht möglich, eine Website zu machen, die alle URLs schon ausgibt und evtl. mit einem Link der NFC-App übergibt (inkl. Schreibschutz)?

**Comment by salendron** [comment]
Webseite wäre einfach. App ist das Problem. Nö Problem ist falsch. Eine App
die das KAnn gibt es nicht, aber das kann man ändern. ;-)

Am 15. Dezember 2012 16:40 schrieb Georg Holzer notifications@github.com:

> Bin grad beim NFC-Tag-Beschreiben.
> Das ist voll mühsam. Wäre es nicht möglich, eine Website zu machen, die
> alle URLs schon ausgibt und evtl. mit einem Link der NFC-App übergibt
> (inkl. Schreibschutz)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/salendron/Pingeborg/issues/28.

## 

<p style="margin-top:10px; margin-bottom:0; padding-bottom:0;
text-align:center; line-height:0"><a target="_blank" href="
http://feeds.feedburner.com/~r/The-engineat/~6/1"><img src="
http://feeds.feedburner.com/The-engineat.1.gif" alt="the-engine.at"
style="border:0"></a></p><p style="margin-top:5px; padding-top:0;
font-size:x-small; text-align:center"><a href="
http://feedburner.google.com/fb/a/headlineanimator/install?id=3i135mstpm4888rbu0cjpa63p4&amp;w=1"
onclick="window.open(this.href, 'haHowto',
'width=520,height=600,toolbar=no,address=no,resizable=yes,scrollbars');
return false" target="_blank">&uarr; Grab this Headline Animator</a></p>
