### ISSUE TITLE
Heatmap für andere Städte

### ISSUE THREAD

**Issue by stephanlendl** [salendron/Pingeborg#46]
Die Heatmap per Aufruf [pingeb_heatmap w=900 h=480 zoom=13 downloads=400] ist immer auf Klagenfurt zentriert.

Sind die Daten auch für andere Städte (Kartenfokus + Filter auf "eigene" Tags) möglich?

**Comment by salendron** [comment]
Ja das geht. Indem man die Map neu zentriert. Dafür gibt es WP Shortcode Parameter für das Kartenzentrum. Siehe -> https://github.com/salendron/Pingeborg/wiki/WP-Shortcodes

**Comment by stephanlendl** [comment]
Danke; hatte ich übersehen. ;-)

Was mir aber noch nicht klar ist: Ist jetzt eine eigene Statistik für unsere Grazer tags möglich (d.h.)
QR vs. NFC  gesamt (auf http://graz.pingeb.org/statistiken/) sind jetzt aber immer alle Daten und nicht nur Graz, oder?
