### ISSUE TITLE
Number of locations in Stats Widget

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#47]
Hi Bruno!
Kannst du das auch mit den API-Settings verbinden?
API Settings - Layers to publish

So soll nur die Anzahl jener Locations angezeigt werden, die auch in der API "scharf" sind. In unserem Fall: Layer 1

**Comment by salendron** [comment]
Hi!

Alles schon erledigt und noch mehr. Neue Version kommt in Kürze. Tests
schon durch. Muss noch Changelog schreiben und publishen und Eierfärben und
Reindling machen. ;-)

ög

Am 29. März 2013 17:08 schrieb Georg Holzer notifications@github.com:

> Hi Bruno!
> Kannst du das auch mit den API-Settings verbinden?
> API Settings - Layers to publish
> 
> So soll nur die Anzahl jener Locations angezeigt werden, die auch in der
> API "scharf" sind. In unserem Fall: Layer 1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/salendron/Pingeborg/issues/47
> .

## 

<p style="margin-top:10px; margin-bottom:0; padding-bottom:0;
text-align:center; line-height:0"><a target="_blank" href="
http://feeds.feedburner.com/~r/The-engineat/~6/1"><img src="
http://feeds.feedburner.com/The-engineat.1.gif" alt="the-engine.at"
style="border:0"></a></p><p style="margin-top:5px; padding-top:0;
font-size:x-small; text-align:center"><a href="
http://feedburner.google.com/fb/a/headlineanimator/install?id=3i135mstpm4888rbu0cjpa63p4&amp;w=1"
onclick="window.open(this.href, 'haHowto',
'width=520,height=600,toolbar=no,address=no,resizable=yes,scrollbars');
return false" target="_blank">&uarr; Grab this Headline Animator</a></p>
