### ISSUE TITLE
Layout Squares

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#48]
Hi Master Bruno!
Ich hätte wieder ein Anliegen: Bei den Squares ... kann man da auch horizontal den gleichen Abstand einbauen wie vertikal? Padding oder Margin oder wie das heißt.

So wären die Squares besser abgetrennt und optisch sieht's auch schöner aus.

**Comment by salendron** [comment]
Klar wird gemacht!

lg
Bruno

Am 30. März 2013 12:21 schrieb Georg Holzer notifications@github.com:

> Hi Master Bruno!
> Ich hätte wieder ein Anliegen: Bei den Squares ... kann man da auch
> horizontal den gleichen Abstand einbauen wie vertikal? Padding oder Margin
> oder wie das heißt.
> 
> So wären die Squares besser abgetrennt und optisch sieht's auch schöner
> aus.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/salendron/Pingeborg/issues/48
> .

## 

<p style="margin-top:10px; margin-bottom:0; padding-bottom:0;
text-align:center; line-height:0"><a target="_blank" href="
http://feeds.feedburner.com/~r/The-engineat/~6/1"><img src="
http://feeds.feedburner.com/The-engineat.1.gif" alt="the-engine.at"
style="border:0"></a></p><p style="margin-top:5px; padding-top:0;
font-size:x-small; text-align:center"><a href="
http://feedburner.google.com/fb/a/headlineanimator/install?id=3i135mstpm4888rbu0cjpa63p4&amp;w=1"
onclick="window.open(this.href, 'haHowto',
'width=520,height=600,toolbar=no,address=no,resizable=yes,scrollbars');
return false" target="_blank">&uarr; Grab this Headline Animator</a></p>

**Comment by salendron** [comment]
Done.
