### ISSUE TITLE
overwrite wordpress settings

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#49]
Hi!

Die meisten WP-Installationen verbieten standardmäßig den Upload einiger Mediendateien. Hab das manuell in der functions.php geändert, ist aber für neue Installationen ein Problem.

Kann man das Codeschnipsel ins Plugin geben, damit die WordPress-Settings überschrieben werden?
Details: http://wordpress.org/support/topic/mobi-and-epub-files-disallowed

Für folgende Medientypen: .epub .mobi .mp3 .aac

Just an idea ;-)

**Comment by salendron** [comment]
Done.
