### ISSUE TITLE
Bug in Zeile 992?

### ISSUE THREAD

**Issue by ghost** [salendron/Pingeborg#51]
Seit kurzem (Update auf WordPress 3.6?) steht das in der Sidebar ober dem Counter. :-(

Warning: Missing argument 2 for wpdb::prepare(), called in /usr/www/users/digira/pingeborg/wp-content/plugins/pingeborg/pingeb_widgets.php on line 36 and defined in /usr/www/users/digira/pingeborg/wp-includes/wp-db.php on line 992

**Comment by salendron** [comment]
Fixed
